//#region  FETCHING_DATA
export const FETCHING_DATA = 'CONTACT_FETCHING_DATA';
export const FETCHING_DATA_SUCCESS = 'CONTACT_FETCHING_DATA_SUCCESS';
export const FETCHING_DATA_FAILURE = 'CONTACT_FETCHING_DATA_FAILURE';
//#endregion
