


require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
platform :ios, '11.0'

# # CocoaPods analytics sends network stats synchronously affecting flutter build latency.
# ENV['COCOAPODS_DISABLE_STATS'] = 'true'

target 'chat_firebase' do


  # permissions_path = '../node_modules/react-native-permissions/ios'
  # pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
  # pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications"
  # pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary"
  # pod 'Permission-PhotoLibraryAddOnly', :path => "#{permissions_path}/PhotoLibraryAddOnly"


  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-async-storage/async-storage'
  # set this and toggle '$RNFirebaseAsStaticFramework' above to test static frameworks)
  use_modular_headers!
  config = use_native_modules!
  # use_frameworks!
  use_frameworks! :linkage => :static

  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec', :modular_headers => false
  $RNFirebaseAsStaticFramework = true # toggle this to true (and set 'use_frameworks!' below to test static frameworks)

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  target 'chat_firebaseTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  # use_flipper!()
  

  post_install do |installer|

    react_native_post_install(installer)

    # Convert all permission pods into static libraries
    # Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}

    # installer.pod_targets.each do |pod|
    #   if pod.name.eql?('RNPermissions') || pod.name.start_with?('Permission-')
    #     def pod.build_type;
    #       # Uncomment the line corresponding to your CocoaPods version
    #       Pod::BuildType.static_library # >= 1.9
    #       # Pod::Target::BuildType.static_library # < 1.9
    #     end
    #   end
    # end



    # if (target.name&.eql?('FBReactNativeSpec'))
    #   target.build_phases.each do |build_phase|
    #     if (build_phase.respond_to?(:name) && build_phase.name.eql?('[CP-User] Generate Specs'))
    #       target.build_phases.move(build_phase, 0)
    #     end
    #   end
    # end
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end


end
