//#region  FETCHING_DATA
export const FETCHING_DATA = 'CHAT_FETCHING_DATA';
export const FETCHING_DATA_SUCCESS = 'CHAT_FETCHING_DATA_SUCCESS';
export const FETCHING_DATA_INSERT_SUCCESS = 'CHAT_FETCHING_DATA_INSERT_SUCCESS';
export const FETCHING_DATA_DEVICE_TOKEN_SUCCESS =
  'CHAT_FETCHING_DATA_DEVICE_TOKEN_SUCCESS';
export const FETCHING_DATA_HISTORY_SUCCESS =
  'CHAT_FETCHING_DATA_HISTORY_SUCCESS';
export const FETCHING_DATA_FAILURE = 'CHAT_FETCHING_DATA_FAILURE';
//#endregion
