//#region  FETCHING_DATA
export const FETCHING_DATA = 'HISTORY_FETCHING_DATA';
export const FETCHING_DATA_SUCCESS = 'HISTORY_FETCHING_DATA_SUCCESS';
export const FETCHING_DATA_FAILURE = 'HISTORY_FETCHING_DATA_FAILURE';
//#endregion
